// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnqryuilboxpgfjceyut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImducXJ5dWlsYm94cGdmamNleXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDYyNjcsImV4cCI6MjA1ODk4MjI2N30.0KrpS1-UGr14KzpzII9RXWmRxcWCKObQElF9rFNUeYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);